// Generated by CoffeeScript 1.6.3
(function() {
  var fs, init, initConfig, loadConfig, path;

  fs = require('fs');

  path = require('path');

  initConfig = require('./config_sample');

  init = function() {
    var defaultValue, dir, i, j, key, params, resultValue, ret, stdin, stdout, tips, value;
    console.log("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
    console.info("第一次使用程序，没有找到当前项目的配置文件，请按照提示输入相应参数 ...");
    console.log("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
    stdin = process.stdin;
    stdout = process.stdout;
    stdin.resume();
    stdin.setEncoding('utf8');
    dir = process.cwd();
    params = [];
    defaultValue = [];
    resultValue = [];
    tips = initConfig._tips;
    delete initConfig._tips;
    i = 0;
    for (key in initConfig) {
      value = initConfig[key];
      params[i] = key;
      defaultValue[i] = value;
      i++;
    }
    j = 0;
    ret = {};
    stdout.write("" + tips[j] + " 当前值 \<" + (process.argv[2] || './') + "\> \n" + params[j] + " :");
    return stdin.on('data', function(chunk) {
      if (chunk === '\n') {
        resultValue[j] = defaultValue[j];
      } else {
        resultValue[j] = chunk.trim();
      }
      j++;
      if (j < i) {
        return stdout.write("请输入" + tips[j] + " 当前值 \<" + defaultValue[j] + "\> \n" + params[j] + " :");
      } else {
        j = -1;
        while (++j < i) {
          ret[params[j]] = resultValue[j];
        }
        console.info("成功保存以下配置保存到 '.m3dsync_config' 请重新执行程序开始监控");
        console.log("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
        console.log(ret);
        console.log("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
        console.info("如需修改配置，直接编辑 '.m3dsync_config' 文件即可");
        fs.writeFileSync('.m3dsync_config', JSON.stringify(ret, null, '  '));
        return process.exit();
      }
    });
  };

  loadConfig = function(confFile) {
    var DEFAULT_CONFIG_FILE_PATH, config, e;
    DEFAULT_CONFIG_FILE_PATH = '../sample.m3dsync_config';
    try {
      config = fs.readFileSync(confFile);
      try {
        config = JSON.parse(config);
        console.log("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
        console.log("+ Using configuration file: " + confFile);
        console.log("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
        return config;
      } catch (_error) {
        console.error("The configuration file \n\t" + confFile + "\nis not a valid JSON file, please check the syntax");
      }
    } catch (_error) {
      e = _error;
      init();
      return void 0;
    }
  };

  module.exports.load = loadConfig;

}).call(this);
