// Generated by CoffeeScript 1.6.3
(function() {
  var fc, md5, path;

  path = require('path');

  md5 = require('MD5');

  fc = {
    dispatchEvent: function(handler, oStatus) {
      var createDirID, createFileID, data, deleteDirID, deleteFileID, dir, file, id, mvdir, nStatus, ndata, ndir, nfile, odata, odir, ofile, _ref, _ref1, _ref2, _ref3, _results;
      nStatus = handler.status();
      if (md5(oStatus) === md5(nStatus)) {
        return;
      }
      odata = JSON.parse(oStatus);
      ndata = JSON.parse(nStatus);
      ofile = {};
      odir = {};
      nfile = {};
      ndir = {};
      mvdir = {};
      deleteDirID = {};
      createDirID = {};
      deleteFileID = {};
      createFileID = {};
      _ref = odata.dir;
      for (dir in _ref) {
        data = _ref[dir];
        if (!ndata.dir[dir]) {
          deleteDirID[data.id] = dir;
        } else if (ndata.dir[dir].id === data.id) {
          delete odata.dir[dir];
          delete ndata.dir[dir];
        } else {
          delete odata.dir[dir];
          delete ndata.dir[dir];
        }
      }
      _ref1 = ndata.dir;
      for (dir in _ref1) {
        data = _ref1[dir];
        createDirID[data.id] = dir;
      }
      for (id in deleteDirID) {
        dir = deleteDirID[id];
        if (createDirID[id]) {
          console.log('mvdir ' + dir + ' -> ' + createDirID[id]);
          mvdir[dir] = id;
          delete deleteDirID[id];
          delete createDirID[id];
        } else {
          console.log("rmdir" + dir);
        }
      }
      for (id in createDirID) {
        dir = createDirID[id];
        console.log("mkdir" + dir);
      }
      _ref2 = odata.file;
      for (file in _ref2) {
        data = _ref2[file];
        if (!ndata.file[file]) {
          deleteFileID[data.id] = file;
        } else if (ndata.file[file].id === data.id) {
          delete odata.file[file];
          delete ndata.file[file];
        } else {
          console.log('Modified ' + file);
          delete odata.file[file];
          delete ndata.file[file];
        }
      }
      _ref3 = ndata.file;
      for (file in _ref3) {
        data = _ref3[file];
        createFileID[data.id] = file;
      }
      for (id in deleteFileID) {
        file = deleteFileID[id];
        if (createFileID[id]) {
          if (!mvdir[path.dirname(file)]) {
            console.log("mvfile " + file + ' -> ' + createFileID[id]);
          }
          delete deleteFileID[id];
          delete createFileID[id];
        } else {
          console.log("delete " + file);
        }
      }
      _results = [];
      for (id in createFileID) {
        file = createFileID[id];
        _results.push(console.log("create " + file));
      }
      return _results;
    }
  };

  module.exports = fc;

}).call(this);
