fs = require 'fs'
url = require 'url'
path = require 'path'
watch = require "watch-project"
remote = require './upload'
fc = require './filechange'
CONFIG = require './config'
jch = require "jch"

console.error = (s)->
  console.log("\u001b[1;31m#{s}\u001b[0m")
# used for log messages generated by other program
console.info = (s)->
  console.log "\u001b[36m#{s}\u001b[0m"
# used for log important messages
console.warn = (s)->
  console.log "\u001b[35m#{s}\u001b[0m"

init = ()->

  target = path.resolve(process.argv[2] || "", '.m3dsync_config')

  CONFIG = CONFIG.load(target)

  # first running this program, will ask user to input configuration informatin rather than start watching
  if not CONFIG
    return


  # check file exists
  if not fs.existsSync CONFIG.path
    console.error "Error: "
    console.log "\tWatching directory '#{ CONFIG.path }' is not Exist!"
    return


  # init local
  console.log "Local : >>>"
  console.log "\tWatching   ... '#{ CONFIG.path }'"
  console.log "\tConnecting ... '#{CONFIG.host}'"
  console.log ""

  # init server
  remote.connect CONFIG.host, CONFIG.pathto


  #dispatch events occured during the program is not running
  #watch.ready ()->
  #  fs.readFile '.m3ddata', {encoding: 'utf-8'}, (err, data)->
  #    return if err
  #    fc.dispatchEvent watch, data


  watch CONFIG.path, (e)->
    #filter .swp files created by vim
    #console.log '\u001b[1;4;35m>>>>>>>>>>>>>>>>>>>\u001b[0m'
    console.log "Local: >>>\u001b[1;4m#{e.type}\u001b[0m [#{e.filename}] (#{(new Date()).toTimeString()})"
    console.log "   old:\t#{e.oid}"
    console.log "   new:\t#{e.nid || e.oid}"

    switch e.type
      when 'mkdir'
        remote.mkdir e.filename
      when 'change', 'create'
        remote.save e.filename, e.oid
        if (path.basename e.filename)[0...3] is 'jch'
          jch.parse(e.filename)
      when 'delete', 'rmdir'
        remote.delete e.filename, e.oid
      when 'mvfile', 'mvdir'
        remote.move e.oname, e.oid, e.filename
      else



  #save watch status for trigger change events next time
  process.on 'SIGINT', ()->
    #fs.writeFileSync '.m3ddata', watch.status()
    do process.exit

module.exports.run = init